# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_backend_promotion_action_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.promotion_action:deleteAction
        _sylius:
<<<<<<< HEAD
            redirect:
                route: sylius_backend_promotion_show
                parameters: {'id': $promotionId}
=======
            redirect: referer
>>>>>>> 2a50dfc58650724c3cd7c772d2f88accef2f3f5d
